<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="diffbot">
    <!-- Constants for robot dimensions -->
    <xacro:property name="mass" value="2.0"/> <!-- 增加质量 -->
    <xacro:property name="width" value="0.5"/> <!-- Square dimensions (widthxwidth) of beams -->
    <xacro:property name="length" value="0.5"/>
    <xacro:property name="height" value="0.061"/>
    <xacro:property name="wheel_length" value="0.03"/> <!-- Link 1 -->
    <xacro:property name="wheel_radius" value="0.1"/> <!-- Link 2 -->
    <xacro:property name="gimbal_height" value="0.03"/>
    <xacro:property name="gimbal_radius" value="0.02"/>
    <xacro:property name="muzzle_height" value="0.05"/>
    <xacro:property name="muzzle_radius" value="0.01"/>

    <material name="orange">
      <color rgba="${255/255} ${108/255} ${10/255} 1.0"/>
    </material>
    <material name="black">
      <color rgba="0.0 0.0 0.0 1.0"/>
    </material>

    <material name="blue">
      <color rgba="0 0 0.8 1"/>
    </material>

    <material name="white">
      <color rgba="1 1 1 1"/>
    </material>

    <link name="base_footprint"/>

    <joint name="base_joint" type="fixed">
      <parent link="base_footprint"/>
      <child link="base_link"/>
      <origin xyz="0.0 0.0 ${height/2 + wheel_radius}" rpy="0.0 0.0 0.0"/>
    </joint>

    <link name="base_link">
      <visual>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <geometry>
          <box size="${length} ${width} ${height}"/>
        </geometry>
        <material name="blue"/>
      </visual>
      <inertial>
        <!--质心位置在此修改 0.001 0.0 0.0-->
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <mass value="${mass}"/>
        <inertia ixx="0.04229" ixy="0.0" ixz="0.0" iyy="0.04229" iyz="0.0" izz="0.08333"/>
      </inertial>
      <collision>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <geometry>
          <box size="${length} ${width} ${height}"/>
        </geometry>
      </collision>
    </link>

    <!-- IMU Link -->
    <link name="imu_link">
      <visual>
        <geometry>
          <box size="0.01 0.01 0.01"/>
        </geometry>
      </visual>
      <inertial>
        <mass value="0.001"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.000001" ixy="0" ixz="0" iyy="0.000001" iyz="0" izz="0.000001"/>
      </inertial>
    </link>

    <joint name="imu_joint" type="fixed">
      <parent link="base_link"/>
      <child link="imu_link"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <xacro:macro name="wheel" params="prefix reflect num">
      <link name="${prefix}_wheel">
        <inertial>
          <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
          <mass value="0.5"/> <!-- 增加轮子质量 -->
          <inertia ixx="0.00129" ixy="0.0" ixz="0.0" iyy="0.00129" iyz="0.0" izz="0.0025"/>
        </inertial>
        <visual>
          <geometry>
            <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
          </geometry>
          <material name="white"/>
        </visual>
        <collision>
          <geometry>
            <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
          </geometry>
        </collision>
      </link>

      <joint name="${prefix}_wheel_joint" type="continuous">
        <origin xyz="0.0 ${reflect*(width/2+wheel_length/2)} ${-height/3}" rpy="${-pi/2} 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="${prefix}_wheel"/>
        <axis xyz="0.0 0.0 1"/>
        <limit effort="103.07" velocity="173.7" upper_limit="1e10" lower_limit="-1e10"/>
        <!-- 添加动力学属性：damping 为粘性阻尼，friction 为静摩擦力 -->
        <dynamics damping="0.01" friction="0.01"/>
      </joint>

      <transmission name="${prefix}_wheel_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="${prefix}_wheel_joint">
          <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="${prefix}_wheel_motor">
          <mechanicalReduction>1</mechanicalReduction>
        </actuator>
      </transmission>
    </xacro:macro>

    <xacro:wheel prefix="left" num="0" reflect="1"/>
    <xacro:wheel prefix="right" num="1" reflect="-1"/>
    
    <gazebo reference="imu_link">
      <gravity>true</gravity>
      <sensor name="imu_sensor" type="imu">
        <always_on>true</always_on>
        <update_rate>100</update_rate>
        <visualize>true</visualize>
        <imu/>
        <plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin">
          <topicName>imu</topicName>
          <bodyName>imu_link</bodyName>
          <updateRateHZ>100.0</updateRateHZ>
          <gaussianNoise>0.0</gaussianNoise>
          <xyzOffset>0 0 0</xyzOffset>
          <rpyOffset>0 0 0</rpyOffset>
          <frameName>imu_link</frameName>
          <initialOrientationAsReference>false</initialOrientationAsReference>
        </plugin>
      </sensor>
    </gazebo>

    <gazebo>
      <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
        <robotNamespace>/</robotNamespace>
      </plugin>
    </gazebo>
</robot>